plugins { id 'com.android.application' }

android {
    namespace 'th.wanwanwan.app'
    compileSdk 35
    defaultConfig {
        applicationId 'th.wanwanwan.app'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '1.1.0'
    }
    signingConfigs {
        release {
            storeFile file('../wanwan-release.p12')
            storePassword System.getenv('WANWAN_STORE_PASSWORD')
            keyAlias 'wanwan'
            keyPassword System.getenv('WANWAN_KEY_PASSWORD')
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-auth:21.2.0'
}
